### ISSUE TITLE
Upgrading to HAOS 12.3 breaks Alsa Audio in Notifier add-on

### ISSUE THREAD

**Issue by ecou2508** [guido-syseng/Hassio-Addons#3]
Notifier Add-on won’t play anymore stereo 44.1 KHz wav audio files since HAOS 12.3 update
Others files play fine but i did not test every formats…
Downgrading OS to 12.2 restores full fonctionality of Alsa Audio in this add-on.
See below captures of Notifier Add-on log, settings of a working file and non-working file.
Thanks.
![2024-05-20 123304 Alsa Audio problem with Notifier Addon and HAOS 12 3 (Core-2024 5 4) - notifier logs](https://github.com/guido-syseng/Hassio-Addons/assets/50460169/b54b9383-adee-4bd5-82d5-5d5dd02751d8)

A still working file properties page:
![2024-05-20 123304 Alsa Audio problem with Notifier Addon and HAOS 12 3 (Core-2024 5 4) - working file](https://github.com/guido-syseng/Hassio-Addons/assets/50460169/0037ff1d-80b1-41e8-9261-5b1595abf005)

A not anymore working file properties page:
![2024-05-20 123304 Alsa Audio problem with Notifier Addon and HAOS 12 3 (Core-2024 5 4) - non-working file](https://github.com/guido-syseng/Hassio-Addons/assets/50460169/cdb4bde5-5150-4764-b748-14e8b27dbc43)

**Comment by guido-syseng** [comment]
I fixed the 44 kHz files issue, at least in my test environment, and created a new version of the Addon. I'm waiting for confirmation from users before declaring the problem solved.

**Comment by ecou2508** [comment]
I just upgraded one of my 2 raspi 4b from OS12.2 to OS12.4:
On OS 12.4 : I still have problems : 44Khz stereo wav file playback is missing the first 0,85 sec of the beginning of the audio. 
The same file plays still fine on OS 12.2
The new version of notifier has been installed on both systems.

I tried a second full reboot of the system but same result !

Nothing in Notifier's log nor in HA logs.

The same audio 44khz/stereo file plays fine with a paplay command in SSH&Web terminal on OS 12.4

Thanks,
Eddy

**Comment by guido-syseng** [comment]
Unfortunately I was unable to reproduce his problem with 44.1 kHz wav audio
files, in my test environment the playback, activated by a button and an
automation, starts immediately and the sound is heard for 13.943 s. I
attach the addon log with Debug option enabled.

[21:28:53] INFO: Notifier is waiting for commands...
[21:29:06] INFO: Notifier is receiving the command: {
  "volume": 10,
  "music": "zgb44.wav"
}
             Overall     Left      Right
DC offset  -0.000006 -0.000006 -0.000003
Min level  -0.076563 -0.076563 -0.071667
Max level   0.068372  0.068372  0.066586
Pk lev dB     -22.32    -22.32    -22.89
RMS lev dB    -39.21    -39.00    -39.42
RMS Pk dB     -29.80    -29.80    -30.31
RMS Tr dB     -53.97    -53.24    -53.97
Crest factor       -      6.83      6.70
Flat factor     0.00      0.00      0.00
Pk count           2         2         2
Bit-depth      29/32     29/32     29/32
Num samples     615k
Length s      13.943
Scale max   1.000000
Window s       0.050
[21:29:19] INFO: Playing executed

I used version 1.1.1 of the addon, installed after deleting the
previous version.
Since I am currently unable to obtain the reported malfunction (no
sound for the first 0.85s), I leave the problem open, waiting for
further information.
Best regards

Guido Gardini


Il giorno gio 4 lug 2024 alle ore 20:23 ecou2508 ***@***.***>
ha scritto:

**Comment by ecou2508** [comment]
Dear Guido,
Can you please try with my file ? I copy it to a shared folder in my GoogleDrive:
https://drive.google.com/drive/folders/11PfALgOI9JN-q95BaY5cwbdWx0HVTyNl?usp=sharing
This wav file has been created with Audacity (free software) and https://freetts.com/ and i did not put any kind of copyright on it... :-)
Great thanks
Eddy

**Comment by ecou2508** [comment]
With debug option enabled, the log has following infos:
![Capture d’écran 2024-07-05 093334](https://github.com/guido-syseng/Hassio-Addons/assets/50460169/3b9141f6-e93e-41a8-bb68-3fca8a613507)

**Comment by guido-syseng** [comment]
I tested the audio file "systeme.desarme.wav" with the new version 1.1.2
that I was preparing and now there is no longer the silence of 0.8s, while
I was able to see that it was present in the previous version 1.1.1. . I
therefore invite you to try this version 1.1.2, which I put into production
a few minutes ago, and let me know the results you get.
Best wishes
Guido Gardini

Il giorno ven 5 lug 2024 alle ore 09:35 ecou2508 ***@***.***>
ha scritto:

**Comment by ecou2508** [comment]
Guido,
1.1.2 plays perfectly my 44.1Khz/stereo files !

Great thanks to you !
Eddy
